### ISSUE TITLE
issue when on update form

### ISSUE THREAD

**Issue by aljabr** [GustavoFenilli/formkit-inertify#5]
hi,

how can i set the data without v-model  on update form? like what you put it in the example code

and is there a way to pass the disabled button if i want to use custom action button?

thank you.

**Comment by GustavoFenilli** [comment]
Those questions are about FormKit itself, not this package check out [FormKit's Documentation](https://formkit.com/essentials/forms)

1. You can set using `:values` or getting the form node and setting its input after a async call `node.inptu(result)`.
2. To use a custom action button you can either get the disabled state using `#default="{ disabled }"` at the form level, or get the form node and read its state manually.
